### ISSUE TITLE
A few questions and suggestions

### ISSUE THREAD

**Issue by burzum** [josegonzalez/cakephp-version#1]
* Wouldn't it be more efficient to store the whole data serialized in a single field instead of using one row per field for the version? What's the reason to do it this way?
* Any chance of having the feature to save associated data as well some time soon?
*  What about adding a `fields` option to the behavior to only version the fields we really want?

**Comment by josegonzalez** [comment]
- Maybe, and I did it this way as I was following the translate behavior.
- If you make a pull request for this, perhaps.
- That makes sense, mind making a PR for this?

**Comment by burzum** [comment]
Bulletlistmania!

* And in the translate behavior it caused performance issues :) Thats why there is ad7six ShadowTranslate that uses a copy of the table that has the translateable fields.
* Sorry, no time and mood, got to many frustration from contributing to other things recently.
* Maybe.
