### ISSUE TITLE
Should "content" field be nullable?

### ISSUE THREAD

**Issue by garethellis36** [josegonzalez/cakephp-version#18]
`CREATE TABLE `version` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `version_id` int(11) DEFAULT NULL,
    `model` varchar(255) NOT NULL,
    `foreign_key` int(10) NOT NULL,
    `field` varchar(255) NOT NULL,
    `content` text,
    `created` datetime NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

The NULLability of the 'content' field is not specified in this SQL. We are getting save failures for new entities with the following error:
>Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'content' cannot be null

We used the following migration:
```php
<?php

use Phinx\Migration\AbstractMigration;

class CreateVersions extends AbstractMigration
{
    public function change()
    {
        //set-up according to https://github.com/josegonzalez/cakephp-version
        $this->table('version')
             ->addColumn('version_id', 'integer', ['null' => true])
             ->addColumn('model', 'string')
             ->addColumn('foreign_key', 'integer')
             ->addColumn('field', 'string')
             ->addColumn('content', 'text')
             ->addColumn('created', 'datetime')
             ->addColumn('user_id', 'integer', ['null' => true])
             ->create();
    }
}
```

Do we need to make the content field nullable?

**Comment by josegonzalez** [comment]
Yeah, if one of the fields in your model is nullable, then that content field will also need to be nullable.
