### ISSUE TITLE
[question] Why we need the EventListener and the VersionListener 

### ISSUE THREAD

**Issue by flashios09** [josegonzalez/cakephp-version#3]
Hi @josegonzalez ,
Thanks for this awesome cakephp3 plugin :+1: 
Sorry for my bad english :(

I wanted to store the whole data serialized in a single field instead of using one row per field for the version so i changed the **beforeSave** callback in the **Version Behavior** and it works. I added also a **Json database type** http://book.cakephp.org/3.0/en/orm/database-basics.html#Cake\Database\Type::map .

I have just a question why we need the **EventListener**, the **VersionListener** and the **bootsrap_cli** ?

**Comment by josegonzalez** [comment]
They are used for [Bake Integration](https://github.com/josegonzalez/cakephp-version#bake-integration)
