### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by arilia** [josegonzalez/cakephp-version#33]
After upgrading to cake 3.6.0 i get many deprecation warning coming from this plugin

just an example

> alias() is deprecated. Use setAlias()/getAlias() instead. - /var/www/myapplication/vendor/josegonzalez/cakephp-version/src/Model/Behavior/VersionBehavior.php, line: 406 [CORE/src/Core/functions.php, line 305]

**Comment by josegonzalez** [comment]
Ah neat. Would you be interested in submitting pull requests for these? I'm quite tied up at work with non-cake stuff, but would be happy to review/merge/release if you can do that :)

**Comment by reloxx13** [comment]
im on 3.6 and no warnings for now, gj :+1:
