### ISSUE TITLE
Versioning of associated table fields

### ISSUE THREAD

**Issue by AvelinoJavier** [josegonzalez/cakephp-version#49]
First of all thanks for developing this plugin. Is it possible to version table association changes?

**Comment by jeremyharris** [comment]
Hi @AvelinoJavier,

What do you mean? If you mean versioning associated data changes, then yes, that's exactly what this plugin does! It doesn't, however, track deletions.

If you're talking about versioning changes done within the table code (eg adding a new association, changing the conditions on another), then no, it doesn't. The plugin is really only for database data.

What kind of use case do you have? I might be able to answer your question better.

**Comment by jeremyharris** [comment]
Correct, it doesn't record additions and deletions, only changes. I'm not sure how it could given how this plugin works. I think you'll need a different audit log library for that.

**Comment by AvelinoJavier** [comment]
It is understood. thanks for the clarification
