### ISSUE TITLE
Seems dependency is only on cake orm

### ISSUE THREAD

**Issue by harikt** [josegonzalez/cakephp-version#8]
Hi @josegonzalez , 

I am notified about this repo by lorenzo . Looking at the repo, I believe this have dependency on the cake/orm rather than on the cake framework itself.

If you think so, I wished this could be a library which can be used by other people who are using cake as a standalone version.

Thank you for considering.

**Comment by josegonzalez** [comment]
PRs welcome!

**Comment by harikt** [comment]
@josegonzalez I have a question probably you could have an answer. 

Is it really necessary to use the `"type": "cakephp-plugin",` . 

Do you think it have no trouble installing on vendor folder ?

**Comment by harikt** [comment]
Hm,... it seems I could not test on the orm , but need the whole framework to get the tests running. Related https://github.com/cakephp/cakephp/issues/6994 .

**Comment by josegonzalez** [comment]
Alright well once tests pass, I am happy to merge. For now, installing all of cakephp/cakephp shouldn't be a big issue for any project, just a minor "cleanliness" annoyance, right?

**Comment by harikt** [comment]
> just a minor "cleanliness" annoyance, right?

The problem is you cannot properly  test / make sure if any of the classes really rely on the framework code.

> Alright well once tests pass, I am happy to merge.

I don't recommend merge as it is for in case if you have problems with the type of package. As it is changed to library it may not use the `cake/composer-installer` and hooks that register the value.

I think it may be good, if we can split this to two if so.

1. library ( this one )
2. A framework (another package) glue which can do the necessary plugin registration for the 1.

**Comment by josegonzalez** [comment]
I dropped the plugin-installer as a requirement. Your PR should work just fine now I think.

Closing as the PR is open.
